print('='*50)
preco = float(input('Seja Bem vindo! \nQual é o preço do produto que deseja desconto? R$ '))
novo = preco - (preco * 5 / 100)
avista = preco - (preco * 15 / 100)
prazo = preco + (preco * 25 / 100)
print('='*50)
print('O produto  que custava R${:.2F}, Na promoção com deconto de 5% fica R${:.2f}'.format(preco, novo))
print('Já com pagamento avísta o produto que custa R${:.2f} desconto de 15% fica R${:.2f}'.format(preco, avista))
print('Para pagamento em 12x o produto de R${:.2f} passara a custar R${:.2f}'.format(preco, prazo))
